#!/usr/bin/env bash
# Install nginx on my 1266-web-02 server.
sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Holberton School" > /usr/share/nginx/html/index.html
sudo sed -i "14i\ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
