#!/usr/bin/env bash
# Installs HAProxy load balancer with the following configurations:

sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*

sudo sed -i '$ a\\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 1366-web-01 35.196.255.156:80 check\n\tserver 1266-web-02  52.73.207.89:80 check' /etc/haproxy/haproxy.cfg

sudo service haproxy restart
