#!/usr/bin/env bash
# Displays a different message in the 4th and 8th iteration of the loop
i=1
while [ $i -le 10 ]
do	
	if [ $i -eq 4 ]
	then
		echo bad luck
	elif [ $i -eq 8 ]
	then
		echo good luck
	else
		echo Holberton School
	fi
	let 'i += 1'
done
