#!/usr/bin/env bash
# Script that returns information about the holbertonschool file
hbtn_file="holbertonschool"
if [ ! -e $hbtn_file ]
then
	echo holbertonschool file does not exist
else
	echo holbertonschool file exists
	if [ ! -s $hbtn_file ]
	then
		echo holbertonschool file is empty
	else
		echo holbertonschool file is not empty
	fi
	if [ -f $hbtn_file ]
	then
		echo holbertonschool is a regular file
	fi
fi
